# all after symbol '#' is comment

# === which communication library to use ===
CC	=	mpiCC      # for ethernet and infiniband networks

CFLAGS	=
LIBS	=	-lm

default:	priklad1 priklad2 priklad3 priklad4 priklad5 priklad6 priklad7 priklad8

priklad1:priklad1.c
	$(CC) $(CFLAGS) -o priklad1 priklad1.c $(LIBS)

priklad2:priklad2.c
	$(CC) $(CFLAGS) -o priklad2 priklad2.c $(LIBS)

priklad3:priklad3.c
	$(CC) $(CFLAGS) -o priklad3 priklad3.c $(LIBS)

priklad4:priklad4.c
	$(CC) $(CFLAGS) -o priklad4 priklad4.c $(LIBS)

priklad5:priklad5.c
	$(CC) $(CFLAGS) -o priklad5 priklad5.c $(LIBS)

priklad6:priklad6.c
	$(CC) $(CFLAGS) -o priklad6 priklad6.c $(LIBS)

priklad7:priklad7.c
	$(CC) $(CFLAGS) -o priklad7 priklad7.c $(LIBS)

priklad8:priklad8.c
	$(CC) $(CFLAGS) -o priklad8 priklad8.c $(LIBS)

clear:
	rm priklad?

